saddlebackdev/react-cm-ui

- src/Modules/Dropdown.react.js
#7043 Drop-down menu opens down even it does not fit the screen 
- Subscribe drop-down menu in multi-select mode to scroll events
- Hidden render of a drop-down menu to determine direction of opening the drop-down menu
- Custom styles to render drop-down menu in a correct position (re-positioning)
> Drop-down menu opens down even it does not fit the screen 

- docs/src/js/components/ElementsInput.react.js
- src/Elements/Input.react.js
BI 7179 [SO] - Update max age delay
* adds 500ms delay before validation
* updates documentation
> [SO] - Update max age delay

- src/Elements/Input.react.js
For some reason, this commit from Dec 5 was not merged
> Fix for Numeric Edit Control 

- src/Elements/Input.react.js
Invoke callback on press spinner buttons
> BUG #7895 [Every] Spin control: spin buttons changes values, but doesn’t save them on Save button

- docs/src/js/components/ModulesDrawer.react.js
- src/Modules/Drawer.react.js
- src/scss/components/Modules/Drawer.scss
* Adds an option for a drawer to open from a left side (also support second wing and other drawer features)
* Updates documentation
> Task [10087] Immersive nav (Tier 3) -- part of PBI [8769] Serving Opportunities 1.1

- src/Modules/Dropdown.react.js
- src/utils/DOMUtils.js
- Resize Window event handler for drop-down menu
- Improved estimation of direction to open drop-down window
> [dev] [9078] Dropdown reposition

- docs/src/js/components/ElementsInput.react.js
- src/Elements/Input.react.js
Makes spinners optional for a numeric control
> [dev] PBI [12246] Enhance Number control to remove Scrolling, but still support keypad on mobile (not just a text box, but a number box)

- src/Elements/Icon.react.js
- src/Elements/Input.react.js
* `Icon` ... expose click `event` in `onClick` handler function prop
* `Input` ... refactor number input up/down icons (spin box controls) `onClick` handling to avoid function binding (and reallocation) in `render()`
> [dev] [No PBI] Small tweaks to `Icon` and `Input`

- docs/src/js/components/ElementsButton.react.js
- src/Elements/Button.react.js
- src/scss/components/Elements/Button.scss
> [dev] Outlined button for PBI AB#11130 Ability to edit an existing event

- src/Views/Card.react.js
Possible fix for initialization of Card View
> [dev] BUG AB#16776 Fixes initialization of  Card View

- src/modules/actionBar.js
- added the ability to disable an action bar button
- better view for icon buttons
@morethanfire, @groberts314 please have a look
> Improvements for Page.ActionBar

- src/modules/pageTable.js
- src/modules/pageTable.scss
@morethanfire, @groberts314  please have a look
> Fixes margins for Page.Table on desktop/mobile modes

- docs/src/modules/pageDemo.js
- package.json
- src/modules/details.js
- src/modules/details.scss
- src/modules/detailsColumn.js
- src/modules/detailsColumnContainer.js
- src/modules/detailsPropTypes.js
- webpack.config.js
> Page Details Expandable Columns

- src/modules/dataGroups.scss
- src/modules/drawer.js
PR contains
- Fixing case sensitive issue while importing drawer related file
- datagroup css fix
> [dev] AB# 21618 Ability to view a person’s occupation data on a person record - [R.2] [adult record only]

- docs/src/modules/pageDemo.js
- package-lock.json
- src/modules/dataGroup.js
- src/modules/dataGroupExpandedRow.js
- src/modules/dataGroups.scss
PR contains :
- Expand feature functionality
- Fixing CSS gutters
- Animation on expand
Simple Preview Video Link
https://www.loom.com/share/7f5103d6e27f4ee18562d3c995dd7f45
> [dev] AB# 21618 Ability to view a person’s occupation data on a person record - [R.2] [block size: 375 - 1386] [adult record only]

- src/collections/tableRow.js
- src/views/card.js
PR contains:
- Fixing text highlighting issue for cards and table rows `onClick` event.
(Other changes are eslint fixes due to autosave)
> [dev] AB#21618 - Ability to view a person’s occupation data on a person record - [R.2] [block size: 375 - 1386] [adult record only] 

- docs/src/modules/pageDemo.js
PR contains:
- Dummy response which we are getting now for person record 2.0, and substituting data to expandable features for personal, contact and occupation. So, it would be just import those codes in hc-dev and getting things completed quickly.
> [dev] AB#21618 - Ability to view a person’s occupation data on a person record - [R.2] [block size: 375 - 1386] [adult record only]

- src/templates/dataGrid.jsx
- src/templates/dataGridTable.jsx
- src/templates/dataGridTableRow.jsx
- src/templates/drawerDataGrid.jsx
- src/templates/pageDataGrid.jsx
Added the ability to specify an own ID for `DataGrid` - each cell of the `DataGrid` has an own ID, this fix is needed to be able to have multiple instances of the `DataGrid` on one page.
> [dev] AB#22234 Ability for a serving opportunity administrator to check in/out a volunteer [B.1] - Room Mgmt [OLD]

- src/templates/pageDetailsWindow.jsx
- Was breaking styling of person record 2.0, because of module type typo.
> [No PBI] [Bug] Design issue for page details column

- src/templates/dataGridTableRow.jsx
@morethanfire please have a look
> [dev] NoPBI Fixes the crash on DataGridTableRow render

- package.json
- src/templates/drawer.jsx
- src/templates/drawer.scss
- src/templates/drawerWing.jsx
- src/templates/drawerWing.scss
No rush in reviewing this and cutting a release. This work was part of a, "I hope this will fix the bug, but most likely won't." It doesn't fix the bug, but we might as well not lose the work.
> Upping the Performance of the Drawer's Animation.

- src/templates/content.scss
PR Contains:
28176 - Fix gutters for add person record drawer with new comps
> [dev] AB#24435 - Ability to add a new person record to the system  - [A.2][student]

- src/atoms/__test__/a.test.js
- src/atoms/a.jsx
Adds `id` prop to `<A>` component
> [dev] [No PBI] Add `id` prop to `<A>` component

- src/templates/actionBar.jsx
- src/templates/actionBarActionsButton.jsx
- Neccessity (I need to overwrite stylings for action button drawer. )
> [dev] [No PBI] - Modify action button drawer component to take custom classes

- docs/src/templates/drawerSubNavigation.js
- docs/src/templates/pageSubNavigation.jsx
PR contains:
- Fixing navigation issue on page/drawer
> [dev] AB#24729 - Ability to perform a basic person search - [B.2]

- src/styles/variables.scss
- src/templates/actionBar.scss
- src/templates/drawer.scss
- src/templates/drawerTitleBar.scss
PR contains:
- Fixed design issues, when using `actionbarButtons` in `Drawer` for smaller viewports(Mobile)
- Refactor widths of `Drawer.TitleBar` & `Drawer.ActionBar` based on new designs
Video Links
Issue:  https://www.loom.com/share/f64d30c0ad9f4e039d57c0d81c690922
After Fix: https://www.loom.com/share/0ab204d0200a402981dfc87d61082f1f
> [dev] PBI AB#24730 Ability to perform a basic person search - [B.2] [mobile]

- src/templates/actionBar.jsx
- src/templates/container.scss
- src/templates/content.scss
PR contains
- Fixed action bar button drawer overlapping issue on drawer when `Drawer.navigation` is included for drawer
Video Links
Issue: [https://www.loom.com/share/bb64155f706545c49c1e08d11e538847](https://www.loom.com/share/bb64155f706545c49c1e08d11e538847)
After fixing: [https://www.loom.com/share/2baeb945df0443debf240e3cee90c492](https://www.loom.com/share/2baeb945df0443debf240e3cee90c492)
> [dev] PBI AB#24730 - Ability to perform a basic person search - [B.2] [mobile]

- docs/src/inputs/prompt.jsx
- docs/src/templates/modal.js
- src/inputs/prompt.jsx
- src/inputs/prompt.scss
- src/inputs/textArea.jsx
- src/templates/modal.js
This PR contains a couple of the following components:
```
<Modal />
<Prompt />
```
These were made to match the designs for notes reminders
[AB#31102](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/31102) | Ability to add a reminder to a note - [K.2.1]
> [dev] AB#31102 - Modal/Prompt changes to match note reminders designs

- src/inputs/radio.jsx
Fixes handling a click on radio item with multi option - in current version it is impossible to unselect a radio item.
> [dev] PBI AB#32635 Ability to create an event - When & Where - [E.1.2] - Recurring Event Re-Design

- src/dataDisplay/icon/icon.jsx
- src/dataDisplay/icon/icon.scss
- src/inputs/button/button.jsx
- src/inputs/dropdownButton/dropdownButton.jsx
- src/inputs/dropdownMenu/dropdownMenu.jsx
- src/inputs/dropdownMenu/dropdownMenu.scss
Added a few props and methods to Icon, DropdownButton, and DropdownMenu.
> [dev] AB#33495 - ActionBar Gap Closures

- docs/src/inputs/dropdownDeprecated/dropdownDeprecated.jsx
- src/inputs/dropdown/dropdown.jsx
This PR will fix two `Dropdown Select` problems:
- current menu renderer do not setup the `is-disabled`, `is-focused`, `is-selected` CSS classes for menu items
- no auto scrolling the menu to selected item
> [dev] PBI AB#35007 Ability to edit an event occurrence – When [G.1.3] Enhancements

- src/inputs/datePickerCalendar/datePickerCalendar.jsx
Fixes handling click on prev/next month buttons
> [dev] BUG AB#36859 [Events] Recurring Events Not Working Correctly

- src/inputs/radio/radio.jsx
Fixes CSS styling for disabled <Radio pill/>
> [dev] PBI AB#27865 Ability to edit an event - Registration Settings - Registration Period [C.1.3]

- docs/package-lock.json
- src/inputs/datePickerCalendar/datePickerCalendar.scss
- src/inputs/datePickerInput/datePickerInput.jsx
- src/inputs/datePickerInput/datePickerInput.scss
- src/inputs/prompt/prompt.jsx
- src/inputs/prompt/prompt.scss
- src/style.scss
- src/styles/theme.js
- src/surfaces/drawer/drawer.jsx
- src/surfaces/drawer/drawer.scss
- src/surfaces/drawerDeprecated/drawerDeprecated.jsx
- src/surfaces/drawerDeprecated/drawerDeprecated.scss
- src/surfaces/modal/modal.jsx
- src/surfaces/modal/modal.scss
- src/surfaces/modal/modalHeader.jsx
Updated `zIndex` in order to stop the bugs that keep popping up time-to-time.
Components updated:
- `./src/inputs/datePickerInput`
- `./src/inputs/prompt`
- `./src/surfaces/drawer`
- `./src/surfaces/drawerDeprecated` (I know...)
- `./src/surfaces/modal`
> [release/9.16.4] BUG AB#37522 - Fixed zIndexes

- src/dataDisplay/personPanel/personPanelSummary.jsx
…list is displaying incorrect age
> [dev] Bug AB#33296: [Person Add 2.0] - Child/Student Records in duplicate list is displaying incorrect age

- src/inputs/select/select.jsx
PR contains:
- Design fix for `Select` component material UI
- Added option to modify creatable option
> [features/cumulative-follow-ups-2.0] [PBI] AB#32340 - [T.2] - Ability to add an action to a rule – Email – create new [Select bug fix]

- src/inputs/dropdown/dropdown.jsx
Just cosmetic changes to scroll selection exactly to the first position:
> [dev] PBI AB#39258 [Events] Create Dynamic Start/End time dropdown UI

- src/layout/containerDeprecated/containerDeprecated.jsx
- src/layout/containerDeprecated/containerDeprecatedActionBar.jsx
- src/surfaces/filtersRail/filtersRail.jsx
> [dev] No AB - Container Deprecated Styling Fixes

- docs/src/app/navigationConstants.js
- docs/src/styleGuide/typography.jsx
- docs/src/styleGuide/typographyGridColumn.jsx
- src/surfaces/filtersRail/filtersRail.jsx
> [dev] No PBI - Filters Rail Over Content Fix and Typography Styles Documentation

- src/inputs/input/__test__/input.test.js
- src/inputs/input/input.jsx
This PR contains fixes for - Issue #253 - Input Number Type Does Not Allow Number To Be Greater Than 1
Closes #253
> [feature/cumulative--10.0.0] No PBI - Input Number Type Does Not Allow Number To Be Greater Than 1

- src/layout/grid/grid.jsx
- src/layout/grid/gridColumn.jsx
- src/layout/grid/gridRow.jsx
- src/layout/page/page.jsx
- src/layout/page/pageDetailsWindow.jsx
- src/surfaces/drawer/drawerDetailsWindow.jsx
* This helps identify the components in React Dev Tools
* Also fix some import path issues in `src/surfaces/drawer/drawerDetailsWindow.jsx`
> [dev] [No PBI] Update components using `forwardRef` to use named callbacks

- src/dataDisplay/banner/bannerItem.jsx
- src/dataDisplay/divider/divider.jsx
- src/dataDisplay/table/tableHeader.jsx
- src/inputs/datePickerCalendar/datePickerCalendar.jsx
- src/inputs/datePickerDeprecated/datePickerDeprecatedCalendar.jsx
- src/inputs/datePickerDeprecated/datePickerDeprecatedDay.jsx
- src/inputs/datePickerDeprecated/datePickerDeprecatedInput.jsx
- src/inputs/datePickerDeprecated/datePickerDeprecatedMonth.jsx
- src/inputs/segmentedControls/segmentedControls.jsx
- src/inputs/segmentedControls/segmentedControlsItem.jsx
- src/surfaces/drawerDeprecated/drawerDeprecated.jsx
some fixes to allow SQ scanner to complete
> [dev] PBI AB#39862 - Stand up SonarQube for code analysis coverage

- docs/src/dataDisplay/popover/index.jsx
- docs/src/dataDisplay/popover/popoverMouseEnterSample.jsx
- docs/src/dataDisplay/popover/popoverSampleControlled.jsx
- docs/src/dataDisplay/popover/popoverSamplePlacement.jsx
- docs/src/dataDisplay/popover/popoverSampleWithJsx.jsx
- src/dataDisplay/header/__test__/header.test.js
- src/dataDisplay/personContactInfo/__test__/personContactInfo.test.js
- src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
- src/dataDisplay/personPanel/__test__/personPanel.test.js
- src/dataDisplay/personPanel/__test__/personPanelDetails.test.js
- src/dataDisplay/personPanel/__test__/personPanelDetailsActionButton.test.js
- src/dataDisplay/personPanel/__test__/personPanelSummary.test.js
- src/dataDisplay/popover/__test__/popover.test.js
- src/dataDisplay/popover/popover.jsx
- src/index.js
- src/inputs/button/button.jsx
- src/inputs/durationPicker/__test__/durationPicker.test.js
- src/inputs/select/select.jsx
- src/navigation/a/__test__/a.test.js
- src/styles/createPalette.js
- src/styles/theme.js
- src/surfaces/filtersRail/__test__/filtersRail.test.js
- src/utils/grow/grow.jsx
- src/utils/grow/index.js
- src/utils/index.js
> [dev] AB#41041 - Refactored Popover to use MUI Popper

- src/styles/createPalette.js
Looks like purple color was missed.
> [dev] PBI AB#21304 Ability to send notifications to checked in volunteers - [N.1]

- docs/package-lock.json
- docs/package.json
- docs/webpack.config.js
- gulpfile.babel.js
- package-lock.json
- package.json
See https://dev.azure.com/saddlebackchurch/Church%20Management/_build/results?buildId=26830&view=logs&j=db40ead0-d549-5fb8-3f02-9e9562a5d19f&t=e130dc5c-1eba-592f-1f04-e10b43691bdb
Adopted suggestion from here:
https://github.com/dlmanning/gulp-sass/issues/780#issuecomment-723098248
> [dev] [No Bug/PBI] Try to fix build issues with `node-gyp` package

- src/dataDisplay/personCoreMilestones/gridColumnAcceptedChrist.jsx
- src/dataDisplay/personCoreMilestones/gridColumnBaptised.jsx
- src/dataDisplay/personCoreMilestones/gridColumnClassBaseballDiamond.jsx
- src/dataDisplay/personCoreMilestones/gridColumnMinistry.jsx
- src/dataDisplay/personCoreMilestones/gridColumnMissions.jsx
- src/dataDisplay/personCoreMilestones/gridColumnSmallGroup.jsx
- src/dataDisplay/personCoreMilestones/personCoreMilestones.jsx
> [hotfix/9.21.0-hotfix] Bug AB#46500, AB#46499 - Person Core Milestone Style Fix and CLASS Became A Member Fix.

- docs/src/layout/page/demo/demo.jsx
- docs/src/layout/page/demo/demoFiltersRail.jsx
- src/layout/page/pageFiltersRail.jsx
- src/surfaces/drawer/drawerFiltersRail.jsx
- src/surfaces/filtersRail/filtersRail.jsx
PR contains:
Only implementation of custom scollbar on Filter rails. But having filter rails height issues.
Need suggestion on fixing it @groberts314 @cbrewer1689  
Video Link: [https://www.loom.com/share/2a67c40ba42843989baf2007423ebc4f](https://www.loom.com/share/2a67c40ba42843989baf2007423ebc4f)
> [dev] AB#35036 [Follow Ups > Sort and Filter][B.2] - Campus list is not aligned properly when you open the dropdown

- src/feedback/snackbar/snackbar.jsx
This fixes warning messages we are getting from MUI about ContentProps.
> [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)

- src/surfaces/actionBar/actionBar.jsx
- src/surfaces/actionBar/actionBarSearch.jsx
For this PBI needs to have an autofocus and a custom placeholder for search input.
> [dev] PBI AB#49205 [BG.1.1] Ability to check in an attendee - select existing person record (relationship exists) (child check-in)

- jest.setup.js
Apply same fix in React CM UI as https://github.com/saddlebackdev/church-management/commit/35389b3862abe1d72d87e60f37df05587bcd5369
( part of https://github.com/saddlebackdev/church-management/pull/4912 )
> [dev] [No Bug/PBI] Fix warning "[JSS] Cannot set property 'parentStyleSheet' of undefined"

- src/inputs/dropdownButton/dropdownButton.jsx
- src/inputs/dropdownMenu/dropdownMenu.jsx
- src/inputs/dropdownMenu/dropdownMenuDivider.jsx
- src/inputs/dropdownMenu/dropdownMenuHeading.jsx
- src/inputs/dropdownMenu/dropdownMenuOption.jsx
These changes allow us devs to be able to accomplish a Dropdown Menu like this...
> [dev] PBI AB#51691: Dropdown Button Enhancements and Fixes

- src/inputs/phoneInput/phoneInput.jsx
Pulling assets from flag-icon-css github repo because the other repo was deleted. Tried to update the library to version 3 but it was too big of a effort and documentation provided easier option
> [dev] Bug AB#57694: [Person Record] Flags are not displayed on the drop down menu in the Phone Number field on Person Record 1.0

- src/inputs/phoneInput/phoneInputCountryDropdown.jsx
PR contains:
Fixed crash issue on PhoneInput
Video Crash Issue Link: https://www.loom.com/share/927f069044f143a8a0f32520bcd9b8f0
> [dev] PBI AB#60272 - [Data Capture > Connection Form > Entries] - When user adds a phone number to an entry the system hangs!

- src/surfaces/actionBar/actionBar.jsx
- src/surfaces/actionBar/actionBarSearch.jsx
added callback on ActionBar to detect when is mobile input selected or not
> [dev] AB#60935 Information on the table is being overlapped

- src/surfaces/drawer/drawerDataGroups.d.ts
PR contains:
- Fixing typescript issues related to `drawerDataGroups`. Some of fields weren't required.
> [dev] AB#73825 - Ability to view ticket information for an attendee from the Registration Roster (attendee drawer)

- docs/package-lock.json
- src/inputs/input/input.jsx
> [dev] AB#86692 -- Ability to Upload Large Video Files

- pipelines/React-CM-UI-Build.yml
Remove CI trigger on dev branch and remove condition code regarding artifacts. Now artifacts generated in both dev and master triggers which do not affect anything.
> [dev] AB#53618 [DevOps] Convert Build Pipelines to Yaml | Update react-cm-ui pipeline.

- src/inputs/phoneInput/phoneInput.scss
Cherry-picked version of #455 from @ardneved
> [hotfix/10.6.8-hotfix-1] Bug AB#97711 - [Connection Forms][Safari] - Public form not rendering phone number country flag icon

- docs/src/inputs/dropdownButton/examples/dropdownButtonExample.jsx
- src/dataDisplay/image/image.jsx
- src/inputs/dropdownMenu/dropdownMenuOption.jsx
- src/surfaces/actionBar/actionBarActionsButtonDrawerOption.jsx
PR contains:
- Additional code improvement removing import of `colorExports` from `image.jsx` & `actionBarActionsButtonDrawerOption.jsx`
> [dev] AB#93147 - Dropdown Button Options not hiding even after clicked

- docs/src/layout/page/demo/demoFiltersRail.jsx
- docs/src/surfaces/drawer/demo/demoDrawer.jsx
- src/layout/page/pageFiltersRail.jsx
- src/surfaces/drawer/drawerFiltersRail.jsx
- src/surfaces/filtersRail/__test__/filtersRail.test.js
- src/surfaces/filtersRail/filtersRail.jsx
Demo Links:
Page Layout: http://localhost:8082/components/layout/page/demo
Drawer Layout: http://localhost:8082/components/surfaces/drawer (Next Step: Click on DemoDrawer, to look for filtersRail Example)
Sketch Mock Up:
> [dev] [No PBI] - Implementing Action Buttons (Apply Filter & Clear All) on filter rails

- docs/src/inputs/checkbox/checkbox.jsx
- docs/src/inputs/input/devSandbox/devSandbox.jsx
- docs/src/inputs/input/examples/exampleInputIsRedacted.jsx
- docs/src/inputs/radio/radio.jsx
- docs/src/inputs/select/devSandbox/devSandbox.jsx
- docs/src/inputs/select/examples/exampleIsRedactedSelect.jsx
- docs/src/inputs/textArea/textArea.jsx
- src/inputs/checkbox/checkbox.jsx
- src/inputs/greyScreenGuard/checkboxScreenGuard.jsx
- src/inputs/greyScreenGuard/index.ts
- src/inputs/greyScreenGuard/inputScreenGuard.jsx
- src/inputs/greyScreenGuard/radioScreenGuard.jsx
- src/inputs/greyScreenGuard/selectScreenGuard.jsx
- src/inputs/input/input.jsx
- src/inputs/radio/radio.jsx
- src/inputs/select/select.jsx
- src/inputs/textArea/textArea.jsx
> [dev] PBI AB#103112 [Data Capture - Connection Form - Entries] Ability to Read a Sensitive Connection Question Answer

- src/dataDisplay/chip/chip.d.ts
- src/dataDisplay/chip/chip.jsx
* Add `onDelete` optional prop to TypeScript types for `<Chip>`
* Add suppression of `title` in the embedded `<Icon>` within `<Chip>` component
> [dev] Small tweaks for `<Chip>` component

- src/inputs/select/select.jsx
[hotfix/10.9.9-hf-1] - Bug [AB#109130](https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_workitems/edit/109130) - [Follow Ups] - Email recipient changed from Text Input to User Search
Description
- conditionally pass onInputChange prop
> [hotfix/10.9.9-hf-1] - Bug AB#109130 - [Follow Ups] - Email recipient changed from Text Input to User Search
