src/Modules/DatePicker.react.js
* Update copy for "Month-To-Date" to be "Past 30 Days" as that more accurately describes the functionality of that preset.
* Selecting a single date when the calendar is in date range mode sets this to both the start and end date.
* Handle some UTC vs. Local quirks with selecting start and end dates of a custom range.  It was consistently sending back start of day (12:00 AM midnight) for the selected days, but sometimes it was Local and other times it was UTC.  Kind of a nightmare for the consuming component to figure out what the user actually intended!  This makes it consistently local.
=> DatePicker tweaks for using it in `dateRange` mode

docs/src/js/components/ElementsComment.react.js, docs/src/js/components/ModulesDropdown.react.js, docs/src/js/components/ModulesPrompt.react.js, src/Elements/Comment.react.js, src/Modules/Dropdown.react.js, src/Modules/Prompt.react.js, src/scss/components/Modules/Dropdown.scss
Add ability to edit and delete comments using the Comment component
Being done in service of Workflows 1.0 User Task Dashboard
[PBI 11063](https://saddlebackchurch.visualstudio.com/DefaultCollection/Church%20Management/_workitems/edit/11063): Ability to leave a comment on a task
[Task 12380](https://saddlebackchurch.visualstudio.com/DefaultCollection/Church%20Management/_workitems/edit/12380): BUG: My Dashboard > Task Details Drawer: Cannot edit/delete comments
Sketch: https://sketch.cloud/s/ORzY2/Pr3OEv
Requirements: https://saddleback.egnyte.com/dl/YoLk2mpHTO
Let's please use this PR as a discussion forum to dial the basic UI/UX of the Comment component.  Then we'll work on the specific placement of the component in the My Dashboard Task Drawer.
* Comment author can edit and/or delete …
=> Make Comment component "editable"

docs/src/js/components/CoreApp.react.js, docs/src/js/components/CoreAppNavigation.react.js, docs/src/js/components/ModulesDurationPicker.react.js, docs/src/js/components/ModulesTimePicker.react.js, src/Elements/Input.react.js, src/Modules/DurationPicker.react.js, src/index.js, src/scss/Style.scss, src/scss/components/Modules/DurationPicker.scss
**Overview**
Adds a **`DurationPicker`** component to the React CM UI library.  This component allows you to specify a length of time by various units (days, hours, minutes, etc.).  As an example, this component will be used to say that Follow Up Tasks (for the "Workflows" feature) are due after X number of days or Y number of hours.
**Background**
As a part of cleaning up some technical debt in the Workflows area (mostly in API/back-end but also some in front-end) I'm going to try and decompose the "Workflow Rule Editor" component into some smaller sub-components (the component in question currently lives alongside other components for the editing of Connection Card [Response Card] Templates).  Currently, something very much like the `DurationPicker` component here exists inside a much …
=> [dev] [part of] PBI [14321] Add DurationPicker component (will be used for Follow Up (Task) Due Date policy)

src/Modules/Drawer.react.js
@morethanfire 
We've found that there was a change made recently that brakes some drawers. 
The change is about overriding onClose property of child in react-cm-ui library, so a child misses the passed arguments.
Here is a small fix that fixes drawers like in Worship services `src/js/components/Admin/WorshipServiceSetup/WorshipServiceDrawer.react.js`
As of now we found 4 such drawers and there are more
=> [dev] [NoPBI] Fixes the issues when Drawer child's onClose was overridden

docs/src/js/components/ModulesDrawer.react.js, src/Modules/Drawer.react.js
Fixes warnings on passing object as title for drawers (too annoying / verbose during debugging)
=> [dev] [NoPBI] Fix React errors on passing an object as a title for Drawer

docs/src/js/components/ElementsImage.react.js, docs/src/js/components/ModulesAccordion.react.js, src/Elements/Icon.react.js, src/Elements/Image.react.js, src/Modules/Accordion.react.js, src/scss/components/Elements/Icon.scss, src/utils/Utils.js
* Add an `xxlarge` size option for `<Icon>` component
* Add logic to scale up Avatar Placeholder (User Icon) image depending on the size parameter passed to the `<Image>` component
* Add additional avatar image samples with various sizes to the Image documentation page
* Resolve ESLINT warnings in `Icon.react.js`, `Image.react.js` and `ElementsImage.react.js` documentation page
The reason for this is I need the Avatar to potentially look like this: 
https://sketch.cloud/s/vxGKM/bgDbkwo
@morethanfire Please review the styles and sizing logic for images and icons thoroughly.  By logic I mean the "translation" from numeric sizes passed to `<Image>` component to a fixed size option (`small`, `medium`, `large`, etc.) for `<Icon>`.  I took a rough guess at it, and was able to get it doing this:
=> [dev] Avatar (User Icon) Image Fixes/Enhancements for PBI AB#16313

src/modules/pageTable.js
The `column.header` could be not only text (e.g. it maybe the `Checkbox` or `div`), so, the header cell key should be generated by index.
=> Fixes generating the key for the Page.Table header cell

docs/src/modules/pageDemo.js, src/modules/actionBar.js, src/modules/actionBar.scss, src/modules/actionBarActionsButton.js, src/modules/actionBarActionsButtonDrawerOption.js
* Action Bar Search
* Pass a `search.onClearClick` passed into column options prop passed to `<Page.ActionBar />` into `<ActionBarSearch />`'s `onClearClick` prop (so, you know, we can actually use it! =)
* Fix ESLINT where possible, otherwise suppress the warnings and errors with comments, all throughout `src\modules\actionBar.js`
* Action Bar Buttons
* Fix some issues with `onClick` bindings for the sub-options
* Fix an issue having to do with positioning and trying to click a sub-option.  In some cases the click first propagated to a different parent option that is visually "underneath" the sub-option but is apparently occupying that position!  Thanks to @morethanfire for the simple fix (suppress "pointer events" when the colliding parent option is hidden)
* Better code and styling …
=> [dev] Fixes in `<ActionBarSearch />` and `<ActionBarActionsButtonDrawerOption />`

docs/src/app/app.scss, docs/src/modules/drawerSubNavigation.js, docs/src/modules/pageDemo.js, docs/src/modules/prompt.js, src/modules/actionBar.scss, src/modules/actionBarActionsButton.js, src/modules/actionBarActionsButtonDrawerOption.js, src/modules/actionBarActionsButtonDrawerSubOption.js, src/modules/details.scss, src/modules/drawer.js, src/modules/prompt.js
Build Prompt functionality into `<Page.ActionsBar />` (specifically the `<ActionBarActionsButton />` for the mobile actions menu) so that various options or sub-options can request and configure a confirmation prompt before their `onClick` action is actually fired.
=> [dev] Page action bar mobile action buttons - Add ability to Prompt

docs/src/modules/pageDemo.js, src/modules/details.js, src/modules/details.scss
In this demo the `Expand` button showing in mobile mode only.
@groberts314 , @morethanfire please have a look
=> PBI AB#20349 [My Ministry > Members] [mobile] - Implement page details banner

src/modules/drawer.js
`<Drawer />` component's new `positionY` prop should only be set to "top" or "bottom" if the new sticky drawer behavior is desired.  It must default to not being set at all.  Having it default to "top" was preventing the "nested toggles" in the page mobile filters drawer from being visible, due to `overflow: hidden;` in the CSS for the sticky drawer.
=> Fix Regression due to 'sticky drawer' feature

src/utils/dateUtils.js
Also:
* Standardize on `_.isNil(foo)` over `foo === null || typeof foo === 'undefined` in a couple of other functions
* Add `TODO/FIXME` comments in `formatShort()` function and new `formatShortWithSpecifiedTz()` function to indicate that using a built-in format pattern with localization support is preferable, but that the nearest one to our hard-coded format uses 4 digit years rather than 2 digit years.  We should definitely note, however, that hard-coding MM/DD/YY is not the best, esp. from a localization standpoint, since many cultures have different conventions (e.g. month and day segments might be swapped).
=> [dev] Add `formatShortWithSpecifiedTz()` function to `DateUtils`

package-lock.json, package.json, src/elements/comment.js
**Main fix:**
* Update the "avatar" image embedded in `<Comment />` (we missed this when we refactored `<Image />` to use `type` prop rather than `avatar` prop).
**Also Fixed:**
* Update version in `package-lock.json`
* Add some `npm` commands to `package.json` to be able to run in production mode
**Side Note/Open Issue:**
So, I noticed something _extremely bizarre_, having to to do with `<Dropdown />` when used as a "button menu thingie" and `<Prompt />`.  On the UI Documentation website, the samples where a `<Dropdown />` button menu thingie should trigger the `<Prompt />` _don't work!_
See:
http://cm-ui-docs.saddleback.com/modules/prompt
http://cm-ui-docs.saddleback.com/elements/comment#editable-comment
However (and this is the really bizarre part):
* It works okay when running CM UI …
=> [dev] [No PBI] Fix Avatar Image in Comment component

docs/package-lock.json, src/templates/drawer.jsx, src/templates/drawerFiltersDrawer.jsx, src/templates/drawerFiltersRail.jsx, src/templates/filtersDrawer.jsx, src/templates/filtersRail.jsx
PR contains:
- Ability to pass custom prop named `mobileMaxWidth`.  It will enable drawer to show stylings as mobile drawers for viewport less than `mobileMaxWidth`
eg: Person record notes drawer for viewport less than 1018px width, should show mobile styling for notes drawer(Default drawer for mobile styling is 767px)
Note: Right now, I am passing `mobileMaxWidth` props to `drawer`, `FiltersDrawer`, `FilterRails`. For future enhancement, I am thinking of passing only `mobileMaxWidth` props to `drawer`. It can pass it to its children (FiltersDrawer, FilterRails). For that, I was thinking of using `React.context`. Please provide any suggestions/ideas for it.
=> [dev] AB#25753 - [Person Record 2.0] [page] [md] - Notes: Need to use mobile notes drawer UX. (All Browsers) 

src/templates/actionBar.jsx, src/templates/actionBarActionsButton.jsx, src/templates/actionBarActionsButtonDrawerOption.jsx, src/templates/actionBarActionsButtonDrawerSubOption.jsx
PR Contains
28175 - Modification on menu for mobile (Now, actionButtons icons and button background color can be changed for both normal and highlight more)
21877 - Modify action buttons for mobile & integrate actions(if no iconTypes are given, remove icon related htmls from code)
=> [dev] AB#24435 - Ability to add a new person record to the system  - [A.2][student]

package.json, src/atoms/__test__/a.test.js, src/atoms/__test__/header.test.js
* Adds `@jest/globals` NPM package as a dev dependency
* In each test fixture, adds line: `import { describe, expect, it } from '@jest/globals';`
For some reason, this is necessary to run the tests on my machine.  Otherwise they were failing with error:
```
Test suite failed to run
ReferenceError: describe is not defined
```
No idea as to why this is, since the tests over in `church-management` repo work just fine without this. ¯\\\_(ツ)\_/¯
=> [dev] [No PBI] Add explicit import of things from `@jest/globals` package

src/templates/dataGrid.jsx, src/templates/dataGridTable.jsx
The issue is that when `DataGrid` has no data the header cell widths are not aligned and we can see the columns of the "sticked table" and the columns of the "scrollable table" at same time. So, this PR should fix that.
=> [dev] BUG AB#27358 [Events Central] - Please remove Phone from the Name column [drill through My Ministry tab]

src/templates/actionBar.jsx, src/templates/actionBarActionsButton.jsx
PR contains-
- When search text box for smaller viewport visible, `Drawer.Content` & `Page.Container` gets overlapped by search text box fixed this issue
After Fix : 
[https://www.loom.com/share/fa1f6206e90a477ca6462c2f09f418d0](https://www.loom.com/share/fa1f6206e90a477ca6462c2f09f418d0)
=> [dev] PBI AB#24730 - Ability to perform a basic person search - [B.2] [mobile]

src/inputs/checkbox.jsx
`htmlFor` was removed because when defining an `id` it caused an onChange to be fired twice upon checking/unchecking a Checkbox.
=> [dev] Checkbox Bug Fix

src/dataDisplay/personPanel/__test__/personPanel.test.js, src/dataDisplay/personPanel/__test__/personPanelDetails.test.js, src/dataDisplay/personPanel/__test__/personPanelSummary.test.js, src/dataDisplay/personPanel/personPanel.jsx, src/dataDisplay/personPanel/personPanelDetails.jsx, src/dataDisplay/personPanel/personPanelSummary.jsx
Person Panel
- Reordered hooks to have all components read the same.
- Passes in `props` to the `makeStyles` hook so we can override the `root` class in parent components.
- Added `className` prop.
- Added an `expect` in the root classes test to make sure it's rendering the override class.
- Added a test to for `className`
Person Panel Summary
- Reordered hooks to have all components read the same.
- Code clean up
- Added `className` prop.
- Added `id` prop.
- Added an `expect` in the root classes test to make sure it's rendering the override class.
- Added a test to for `className`
- Added a test to for `id`
Person Panel Details
- Reordered hooks to have all components read the same.
- Added `className` prop.
- Code clean up
=> [dev] AB#24428 - Added Classes and ID Props to PersonPanel Components

src/dataDisplay/table.jsx, src/dataDisplay/tableHeaderCell.jsx
This PR contains the fix for the following bug:
[32766 - [react-cm-ui][stycky table] Sticky behavior not working after some unexpected library merges](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/32766)
=> [dev] AB#32766 - Sticky table behavior not working after some unexpected library merges

package-lock.json, src/layout/page/pageContent.jsx
Relates to Bug [AB#34710](https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_workitems/edit/34710)
=> [hotfix/9.15.2] fix: add missing `px` to JSS style rules on `<PageContent>`

src/inputs/dropdownButton/dropdownButton.jsx
When `<DropdownButton />` is clicked to toggle open the menu, stop propagation of the click event.
This is needed for a use case in Rules 2.0 feature work; see for example: https://www.sketch.com/s/b7836185-bf30-4024-bedb-530069a04c05/a/lMVaMv.  In those cases, the `...` is a `<DropdownButton />` action menu, but the "panel" that it resides in is also clickable for selection.  When the dropdown menu is activated, we don't want to also click the whole panel to select it.
=> [dev] [No Bug/PBI] Stop Propagation on click of <DropdownButton />

docs/src/layout/page/demo/demo.jsx, src/surfaces/filtersDrawer/filtersDrawer.jsx, src/surfaces/filtersDrawer/filtersDrawerNestedTogglesValueLabel.jsx
This PR should align the functionality of the Filter's nested toggles with `Dropdown`:
- Added `singleSelection` feature;
- Added `clearable` feature (to be able to create the single selection switch)
- Allowing to use just `value` data for selection;
Also improved Filter's `multiSelect` option:
- Allowing to use just `value` data for selection;
=> [dev] PBI AB#36142 Update Events Central with Mobile Components - Overview Page

src/dataDisplay/personPanel/__test__/personPanelDetails.test.js, src/dataDisplay/personPanel/personPanelDetails.jsx, src/dataDisplay/personPanel/personPanelDetailsActionButton.jsx
This PR contains changes for `<PersonPanelDetailsActionButton />`:
- It allows to disable the button.
- It allows to set a custom label.
We're using this capabilities in the client for validations on Serving Opps volunteer/schedule rosters disabling the select record button with a label "Already Scheduled" or "Already on Roster".
Here's the [design](https://www.sketch.com/s/a38825f5-c93b-46e1-a4e9-6adb92897d38/a/m1bRo38).
=> [dev] No PBI - Enhancing Person Panel Select Record button for Client's Add Person V2

src/dataDisplay/dataCards/dataCards.jsx, src/dataDisplay/dataGrid/dataGrid.jsx, src/dataDisplay/dataGroups/dataGroups.jsx, src/surfaces/drawer/drawerActionBar.jsx, src/surfaces/drawer/drawerContainer.jsx, src/surfaces/drawer/drawerContent.jsx, src/surfaces/drawer/drawerDataCards.jsx, src/surfaces/drawer/drawerDataGrid.jsx, src/surfaces/drawer/drawerDataGroups.jsx, src/surfaces/drawer/drawerDetailsWindow.jsx, src/surfaces/drawer/drawerFiltersDrawer.jsx, src/surfaces/drawer/drawerFiltersRail.jsx, src/surfaces/drawer/drawerNavigation.jsx, src/surfaces/drawer/drawerTitleBar.jsx, src/surfaces/drawer/drawerWing.jsx
Added some `dataTestId` props to the drawer components.
=> [dev] AB#48476: [G.1.1] - Ability to quick create multiple serving opportunities (one-time event)

docs/src/app/navigationConstants.js, docs/src/global/componentVersionIdentifier.jsx, docs/src/inputs/select/devSandbox/devSandbox.jsx, docs/src/inputs/timePicker/api/api.jsx, docs/src/inputs/timePicker/api/index.js, docs/src/inputs/timePicker/constants.js, docs/src/inputs/timePicker/devSandbox/devSandbox.jsx, docs/src/inputs/timePicker/devSandbox/index.js, docs/src/inputs/timePicker/examples/exampleDefaultTimePicker.jsx, docs/src/inputs/timePicker/examples/exampleDisabledTimePicker.jsx, docs/src/inputs/timePicker/examples/exampleNestedTimePicker.jsx, docs/src/inputs/timePicker/examples/exampleRangeTimePicker.jsx, docs/src/inputs/timePicker/examples/exampleTimePickerWithCustomTimeZoneOptions.jsx, docs/src/inputs/timePicker/examples/exampleTimePickerWithZoneMatchProp.jsx, docs/src/inputs/timePicker/examples/exampleTimePickerWithoutTimeZoneSelect.jsx, docs/src/inputs/timePicker/timePicker.jsx, src/inputs/timePicker/timePicker.jsx, src/inputs/timePicker/timePicker.scss, src/inputs/timePicker/timePickerCreatableOption.jsx, src/versions.js
**Main functional change:**
Add prop `showTimezone` (optional; defaults to `true`) to `TimePicker` component to be able to optionally suppress the Time Zone Select.  Done in service of PBI [AB#25925](https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_workitems/edit/25925) because we need a time of day selector in the filters rail for Connection Forms 2.0 entries but not a Time Zone selector (no comp of this, but it's in the [requirements](https://saddleback.egnyte.com/navigate/file/ca010ee4-562d-4e56-b9e0-01e6c46d207f) (see [V.2]).
**Other Enhancements:**
* Cleanup ESLINT issues in `TimePicker` component source file
* Replace `Dropdown` controls with `Select` controls in `TimePicker` component
* Try to improve the behavior where the popover closes when you're …
=> [dev] PBI AB#25925 [V.2] - Ability to sort & filter entries for a connection form - Add Prop to optionally Suppress Time Zone Select in TimePicker

src/dataDisplay/personPanel/personPanelDetails.jsx, src/dataDisplay/personPanel/personPanelSummary.jsx
PR contains:
- Modification of default props for person panel component
- If `personId` isn't passed for `summaryData` then don't display personId
#note: @War777 I have been reverting some code which I believe was changed by you. Could you please verify it once?
=> [dev] AB#25926 - [W.2] - Ability to create an entry for a connection form - Modification of default props on person panel react-cm-ui component 

src/dataDisplay/image/image.jsx
This will allow us to render `<Image type="person" />` (It the image was always rendering the `user` icon).
**Before:**
**After:**
=> [dev] No PBI - Fixing Image type prop (it was always rendering 'user').

docs/src/app/navigationConstants.js, docs/src/inputs/datePickerInput/api/api.jsx, docs/src/inputs/datePickerInput/api/index.js, docs/src/inputs/datePickerInput/datePickerInput.jsx, docs/src/inputs/datePickerInput/devSandbox/devSandbox.jsx, docs/src/inputs/datePickerInput/devSandbox/index.js, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputBasic.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputDisabled.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputEvents.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputExcludeDates.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputFilterDates.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputFluid.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputIncludeDates.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputLabel.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputMaxDate.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputMinDate.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputOnChange.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputOnMonthChange.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerInputRange.jsx, docs/src/inputs/datePickerInput/examples/exampleDatePickerinputLocale.jsx, docs/src/inputs/timePicker/devSandbox/devSandbox.jsx, src/inputs/datePickerInput/__test__/datePickerInput.test.js, src/inputs/datePickerInput/datePickerInput.jsx, src/inputs/input/input.jsx, src/versions.js
**[Product Backlog Item AB#58900](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/58900) | [AI.2.1] - Ability to export a list of entries (Export for Connection Forms 2.0)**
See:
https://github.com/saddlebackdev/church-management/pull/5767 (esp. https://github.com/saddlebackdev/church-management/pull/5767#discussion_r777645030)
https://github.com/saddlebackdev/church-management/pull/5794
**Scope of Work:**
* Add `fluid` prop to `<DatePickerInput>`
* Add `dataTestId` support for `<DatePickerInput>` and add a unit test fixture for it, testing basic render and `onChange` event handling.
* Also had to add `dataTestId` support for `<Input>`.
* When you specify a `dataTestId` for `<DatePickerInput>` it actually is passed into the `<Input>` and ends up as a …
=> [dev] Related to AB#58900 DatePickerInput enhancements

docs/src/layout/page/demo/demo.jsx, src/dataDisplay/dataGroups/__test__/dataGroups.test.js, src/dataDisplay/dataGroups/dataGroups.jsx, src/surfaces/actionBar/actionBar.jsx
This fixes the following warning (and makes the `data-testid` actually useful!)
```
react_devtools_backend.js:4061 Warning: React does not recognize the `dataTestId` prop on a DOM element.
If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `datatestid` instead.
If you accidentally passed it from a parent component, remove it from the DOM element.
in div (created by DataGroups)
in DataGroups (created by PageDataGroups)
in PageDataGroups (created by [Some Component Using Page Data Groups])
...
```
Also adds a unit test fixture for `<DataGroups>` and fixes a typo I noticed in `<DemoPage>` in the docs.
=> [dev] [No Bug/PBI] Fix `data-testid` issue for `<DataGroups>`

src/inputs/checkbox/checkbox.jsx
Defect with the `<Checkbox>` component noticed while troubleshooting the following:
**[Bug AB#68147](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/68147) | [Connection Cards > Follow Ups > Entries] - User is able to check and or uncheck disabled fields of questions in My follow Ups task's entry, in the Person Record drawer**
This fix is _NOT_ required the fix the HC Bug (which was addressed in https://github.com/saddlebackdev/church-management/pull/6085 by switching to use `disabled` instead of `disable`).  But it seems like something we _should_ fix.
=> [dev] Bug AB#68147 `<Checkbox>`es disabled with `disable` can be still be clicked

docs/src/inputs/select/devSandbox/devSandbox.jsx, docs/src/inputs/select/examples/exampleErrorSelect.jsx, src/inputs/input/input.jsx, src/inputs/select/select.jsx
**[Product Backlog Item AB#69478](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/69478) | [B.2.1.0] - Ability to submit a form entry from a web page _[Submitting a form via web with people required fields]_**
As a part of this work, for improved form validation UI/UX on the public facing Connection Form, I am enhancing React CM UI `<Select>` component to add support for the `error` prop present in most of our other input components.
=> [dev] Related to PBI AB#69478 - Add `error` prop support for `<Select>` component

docs/src/inputs/select/examples/exampleMultipleSelect.jsx, src/inputs/select/select.jsx
* Fix the border and background colors in the selected item "chips" / "tags" / "labels" / whatevers that appear within the `<Select>` control.
* Also make the `<Select>` a bit wider in the example on the Docs page
**Broken (Production UI Docs Site)**
**Fixed (Local UI Docs Site)**
=> [dev] [No Bug/PBI] Fix multiple select selected item styling issue

src/inputs/dropdownButton/dropdownButton.jsx, src/inputs/dropdownMenu/dropdownMenu.jsx
This fixes a bug in allowing the `DropdownMenu` inside the `DropdownButton` to automatically close when the page is clicked outside of the button. It also adds a couple of props to allow overriding the horizontal positioning of the `DropdownMenu` to accommodate some updated designs that have right-aligned menus.
=> [dev] AB#92442 [React Library] Refactor UI Library for Dropdown Menus and Dropdown Buttons

src/inputs/dropdownMenu/dropdownMenu.jsx
Add defensive check on `parentContainer` before de-referencing it to call `contains()` method in `onClickOutside()` function, which can cause a runtime error if it's nullish.
=> [dev] [No Bug\PBI] Prevent crash in Dropdown Menu component

src/inputs/phoneInput/phoneInput.scss
[dev][hotfix/1.62.3] - Bug [AB#97711](https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_workitems/edit/97711) - [Connection Forms][Safari] - Public form not rendering phone number country flag icon
Description
- height and width added to svg icon used inside input flag as on safari it is required for svg's to show
cm-ui doc screenshot on safari
local changes screenshot on safari
=> [dev][hotfix/1.62.3] - Bug AB#97711 - [Connection Forms][Safari] - Public form not rendering phone number country flag icon

docs/src/app/navigationConstants.js, docs/src/dataDisplay/image/api/api.jsx, docs/src/dataDisplay/image/api/index.js, docs/src/dataDisplay/image/devSandbox/devSandbox.jsx, docs/src/dataDisplay/image/devSandbox/examples/exampleAvatarImages.jsx, docs/src/dataDisplay/image/devSandbox/examples/exampleImage.jsx, docs/src/dataDisplay/image/devSandbox/examples/exampleImageSizes.jsx, docs/src/dataDisplay/image/devSandbox/index.js, docs/src/dataDisplay/image/image.jsx, src/dataDisplay/image/__test__/image.test.js, src/dataDisplay/image/image.jsx
* Be able to stop `<Image>` component from adding CSS background image by specifying new prop
* Update documentation style for `<Image>` component
=> [dev] [No Bug/PBI] Add `suppressBackgroundImage` prop to `<Image>` component

src/dataDisplay/image/image.jsx
It needs to not have an extension because the SCSS source file will get converted to CSS and exported as such, so we need to be able to resolve the CSS file when the component is used (e.g. within HC Admin).
Otherwise, we get this error when doing `npm install` in `church-management`:
```
ERROR in ./node_modules/@saddlebackchurch/react-cm-ui/core/dataDisplay/image/image.js
Module not found: Error: Can't resolve '../../styles/colorExports.scss' in 'C:\Projects\Saddleback\cm-clean\client\node_modules\@saddlebackchurch\react-cm-ui\core\dataDisplay\image'
@ ./node_modules/@saddlebackchurch/react-cm-ui/core/dataDisplay/image/image.js 16:43-84
@ ./node_modules/@saddlebackchurch/react-cm-ui/core/dataDisplay/image/index.js
@ ./node_modules/@saddlebackchurch/react-cm-ui/core/dataDisplay/personPanel …
```
=> [dev] [No Bug/PBI] Fix `colorExports` SCSS/CSS import in `<Image>` component

src/surfaces/actionBar/actionBarSearch.jsx
This is a minor regression with the newer functionality in `<ActionBarSearch>` where a `<Select>` can be combined with the search input, in order to help give context to a search term (to aid certain back-end calls that require this to correctly process searches where we're not just using a full-text search powered by ElasticSearch), introduced in #452.  Some validation logic resulted in a console warning about not using this new feature correctly, even if _consumer was not using it at all!_  This change corrects that issue.
=> [dev] [No Bug/PBI] Fix improper console warning in `<ActionBarSearch>`

src/inputs/selectNext/selectNext.tsx
[Bug 102323](https://dev.azure.com/saddlebackchurch/Church%20Management/_workitems/edit/102323): [Finance > COA > Edit Sub Account] - User can Edit the "Sub Account's" segments code numbers, in the "Edit Sub Account" drawer.
=> [dev] AB#102323 [Finance > COA > Edit Sub Account] - User can Edit the "Sub Account's" segments code numbers, in the "Edit Sub Account" drawer.

src/surfaces/drawer/drawerTitleBar.scss
This PR addresses an old annoyance that's been around for a while regarding the 'close' button on a filter rail drawer overlapping the 'apply' button when filters are selected. Visually looks pretty much the same as before, just easier to interact with.
=> [dev] Bug AB#44007 [Automated Test][Mobile][Ministry Central] Close button div overlapping on apply filter button

src/surfaces/modal/modal.jsx
[dev][hotfix/1.72.0] - Bug [AB#105699](https://dev.azure.com/saddlebackchurch/b8a0d0bb-a4fe-48e3-9a60-2f1440145fc4/_workitems/edit/105699) - [Connection Forms] Unable to print entries
Description
- isOpen prop defensive check added to trigger support onClickOutside behavior
=> [dev] - Bug AB#105699 - [Connection Forms] Unable to print entries

src/dataDisplay/chip/chip.d.ts
During the work on the PBI I found that `ChipPropTypes` doesn't include the `label` property
https://github.com/saddlebackdev/church-management/pull/9551
=> [dev] PBI AB#107487 [Data Capture] Ability to set Settings & Preferences of Connection Forms

src/dataDisplay/chip/chip.d.ts
* It is using actual colors from the palette, not "semantic" colors.
* Also add `disabled` prop
=> [dev] [No PBI Correct `color` type for `<Chip>` TypeScript declaration

docs/package-lock.json, docs/package.json, docs/src/app/jssPreset.js, docs/src/index.jsx, docs/template.ejs, docs/webpack.config.js
Trying to fix regression in the [CM UI Docs Website](https://cm-ui-docs.saddleback.com/) after #495.
This is a screenshot of UI Docs w/ React CM UI 10.11.0 ([Build 20240523.1](https://dev.azure.com/saddlebackchurch/Church%20Management/_build/results?buildId=103213&view=results) / [Release 369](https://dev.azure.com/saddlebackchurch/Church%20Management/_releaseProgress?_a=release-pipeline-progress&releaseId=29143)):
This is the prior release - React CM UI 10.10.1 ([Build 20240501.2](https://dev.azure.com/saddlebackchurch/Church%20Management/_build/results?buildId=101916&view=results) / [Release 368](https://dev.azure.com/saddlebackchurch/Church%20Management/_releaseProgress?_a=release-pipeline-progress&releaseId=28788)) _(presently redeployed to prod)_
With the change set in this PR, it's …
=> [dev] PBI AB#97569 Try and fix UI Docs website after #495
